version: '3'

services:
  web:
    build: 
      context: .
      args: 
        - SLACK_SECRET=${SLACK_SECRET}
    image: aytra/slackmiddleware:v3.7
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=local
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"