trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
- name: registryConnection
  type: string
  default: 'dockerhub'

steps:
- task: Docker@2
  displayName: 'Docker login'
  inputs:
    containerRegistry: ${{ parameters.registryConnection }}
    command: login
    addPipelineData: false
    addBaseImageData: false
