# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/K8s'
    artifact: 'kubernetes manifest'
    publishLocation: 'pipeline'
  
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'kubernetes manifest'
    targetPath: '$(Pipeline.Workspace)/manifest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks-devops-prod-escalation-manager-Slack-sDesk-Middleware'
    namespace: 'slack'
    manifests: |
          $(Pipeline.Workspace)/manifest/configmap.yaml
          $(Pipeline.Workspace)/manifest/Slack_deployment.yaml
          $(Pipeline.Workspace)/manifest/Redis_deployment.yaml

          
